// Navbar
export const SET_LOADING_SCREEN = "SET_LOADING_SCREEN";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

// Styles
export const SET_OPENER_SCREEN_DONE = "SET_OPENER_SCREEN_DONE";
export const SET_PORTFOLIO_READY = "SET_PORTFOLIO_READY";
export const SET_PORTFOLIO_DESTROY_WELCOME = "SET_PORTFOLIO_DESTROY_WELCOME";
export const SET_BG_IMG_LOADED = "SET_BG_IMG_LOADED";
export const SET_PAGE_GRADIENT = "SET_PAGE_GRADIENT";
export const SET_PAGE_VISITED = "SET_PAGE_VISITED";
export const SET_CURSOR_BTN = "SET_CURSOR_BTN";
export const SET_TYPE_TEXT_ANIM_FINISHED = "SET_TYPE_TEXT_ANIM_FINISHED";
export const SET_W_IMAGE_SLIDER_CLOSED = "SET_W_IMAGE_SLIDER_CLOSED";
export const SET_SHOW_MIRROR_SLIDESHOW = "SET_SHOW_MIRROR_SLIDESHOW";
export const SET_SHOW_MISC_WORKITEM_SLIDESHOW = "SET_SHOW_MISC_WORKITEM_SLIDESHOW";
export const SET_WORK_ITEM_OPEN = "SET_WORK_ITEM_OPEN";
export const SET_MISC_WORK_ITEM_OPEN = "SET_MISC_WORK_ITEM_OPEN";
export const SET_IS_TOUCH_SCREEN = "SET_IS_TOUCH_SCREEN";
export const SET_TOUCH_RECT_REVEALED = "SET_TOUCH_RECT_REVEALED";
export const SET_HIDE_PULLNAVBTN = "SET_HIDE_PULLNAVBTN";
export const SET_MYWORKS_READY = "SET_MYWORKS_READY";
export const SET_MOBILE_MODE = "SET_MOBILE_MODE";
export const SET_BROWSER_NAME = "SET_BROWSER_NAME";
export const SET_WI_FULL_WRAPPER_SHADOW = "SET_WI_FULL_WRAPPER_SHADOW";
export const MISC_WI_SHADOW = "MISC_WI_SHADOW";
export const SET_W_CONTAINER_IN_POSITION_SHOWING = "SET_W_CONTAINER_IN_POSITION_SHOWING";
export const SET_FINGER_POINTER_MB_DISMISSED = "SET_FINGER_POINTER_MB_DISMISSED";
export const STARS_SHOWING = "STARS_SHOWING";
export const DOCUMENT_HAS_FOCUS = "DOCUMENT_HAS_FOCUS";

// Work Item Sequence Styles
export const SET_WI_IMAGE_LOADED = "SET_WI_IMAGE_LOADED";